name: Android build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/android.yml'
      - 'android/**'
      - 'common/**'
      - 'example/android/**'
  pull_request:
    paths:
      - '.github/workflows/android.yml'
      - 'android/**'
      - 'example/android/**'

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Restore yarn workspaces
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Install example app dependencies
        run: yarn install
        working-directory: example
      - name: Build android example app
        run: ./gradlew assembleDebug
        working-directory: example/android
  android-build-fabric:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Restore yarn workspaces
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Install example app dependencies
        run: yarn install
        working-directory: example
      - name: Build android example app with new arch enabled
        run: ./gradlew assembleDebug -PnewArchEnabled=true
        working-directory: example/android
