name: JavaScript tests

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/js.yml'
      - 'yarn.lock'
      - '**/*.json'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
  pull_request:
    paths:
      - '.github/workflows/js.yml'
      - 'yarn.lock'
      - '**/*.json'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'

jobs:
  js-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Restore yarn workspaces
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
